#
# Druid: a high performance, real-time analytics database that delivers sub-second queries on streaming and batch data at scale and under load.
# https://github.com/apache/druid/blob/26.0.0/distribution/docker/docker-compose.yml
#
volumes:
  metadata-data: {}
  middle-data: {}
  historical-data: {}
  broker-data: {}
  coordinator-data: {}
  router-data: {}
  druid_shared: {}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - metadata-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1

  coordinator:
    image: apache/druid:26.0.0
    container_name: coordinator
    volumes:
      - druid_shared:/opt/shared
      - coordinator-data:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - ./config/environment

  broker:
    image: apache/druid:26.0.0
    container_name: broker
    volumes:
      - broker-data:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - ./config/environment

  historical:
    image: apache/druid:26.0.0
    container_name: historical
    volumes:
      - druid_shared:/opt/shared
      - historical-data:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - ./config/environment

  middlemanager:
    image: apache/druid:26.0.0
    container_name: middlemanager
    volumes:
      - druid_shared:/opt/shared
      - middle-data:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - ./config/environment

  router:
    image: apache/druid:26.0.0
    container_name: router
    volumes:
      - router-data:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - ./config/environment
